project:
  type: website
  output-dir: docs

website:
  title: "Angela Larson"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - csv.qmd
      - Projects.qmd
      - research.qmd

format:
  html:
    theme:
      - styles.scss
    mainfont: Sen
    toc: true
    page-layout: full

editor: visual

